### ISSUE TITLE
Hunt for breaking change since R8

### ISSUE THREAD

**Issue by emilyeros** [sharedstreets/curb-wheel#106]
R8 was created on 6/12. Since then, we've committed code that handles graph segmentation, fixes a data export bug, includes a user location puck on the map, and makes UI improvements. All of this works successfully on the simulator. But when we tried to cut R9, we found breaking changes.

We need to start with `master` as of 6/12 and test out each commit on the pi until we find the breaking change, then fix it. I'll add Slack history and screenshots below that document the strugglebus of issues in R9.

**Comment by emilyeros** [comment]
<img width="838" alt="Screen Shot 2020-07-21 at 10 38 11 AM" src="https://user-images.githubusercontent.com/9657971/88087839-64562700-cb3e-11ea-8f46-8d71136f1562.png">

<img width="998" alt="Screen Shot 2020-07-21 at 10 38 36 AM" src="https://user-images.githubusercontent.com/9657971/88087846-66b88100-cb3e-11ea-801c-1ae0b7e79164.png">

<img width="954" alt="Screen Shot 2020-07-21 at 10 38 52 AM" src="https://user-images.githubusercontent.com/9657971/88087857-69b37180-cb3e-11ea-8961-de8d9b8b861c.png">


Where we landed: @peterqliu was able to start with R8 and move the `static` directory on without problems, which included the last month of UI improvements. This was a workaround but we still need to isolate the problem to get the rest of the code changes incorporated.

**Comment by russbiggs** [comment]
The map not loading seems to be an issue with fetching the style.json from TileServer.  hardcoding the url in map.js to:
http://10.3.141.1:8080/styles/basic-preview/style.json. I'm seeing an ERR_CONNECTION_REFUSED but its not clear what happened exactly

**Comment by emilyeros** [comment]
https://github.com/sharedstreets/curb-wheel/tree/r8-hotfix seems to fix this; russ will create a PR

**Comment by emilyeros** [comment]
closed - issue addressed as part of app overhaul
