### ISSUE TITLE
remove parking aisles from graph segmentation

### ISSUE THREAD

**Issue by emilyeros** [sharedstreets/curb-wheel#111]
We removed service roads from the graph but I noticed that some roads tagged as `highway=service` + `service=parking_aisle` were still included. Let's exclude these since we're aiming to include residential roads and higher in the graph.

Here's where I found these in Bend:
![IMG_3235](https://user-images.githubusercontent.com/9657971/88232587-f89db800-cc2a-11ea-9243-22f19047a4e3.PNG)

![image (12)](https://user-images.githubusercontent.com/9657971/88232627-0e12e200-cc2b-11ea-8e69-0370900d012d.png)

Just in case, I ran overpass queries on Seattle, Portland, and Washington DC and found no instances where `service=parking_aisle` was used on public ROW and residential streets.

**Comment by emilyeros** [comment]
Merged into master as part of https://github.com/sharedstreets/curb-wheel/pull/112

Here's the same area with parking aisles removed:

<img width="1160" alt="Screen Shot 2020-07-22 at 3 24 46 PM" src="https://user-images.githubusercontent.com/9657971/88235521-e3775800-cc2f-11ea-831e-9ab17ac5b89c.png">

**Comment by russbiggs** [comment]
Closed since its has been merged, reopen if there is more work needed on this.
