### ISSUE TITLE
Digitizer missing map

### ISSUE THREAD

**Issue by molliemcardle** [sharedstreets/curb-wheel#114]
Testing the digitizer and the view portal is missing the map, however the data from surveying all seems to be showing (on right)
![Screen Shot 2020-07-24 at 10 53 21 AM](https://user-images.githubusercontent.com/44101636/88421696-d37d8680-cd9d-11ea-8a51-b58eb04c34b8.png)

**Comment by peterqliu** [comment]
@molliemcardle thanks for the report! It looks like the styling is broken for the page from a missing CSS, but I haven't been able to reproduce this. Are you on master, and can you screenshot the browser console?

**Comment by emilyeros** [comment]
This issue occurred because the digitizer was being run off the Pi. We aren't going to fix this because we don't intend for people to run the digitizer on the Pi - better to do this (for now) on the simulator. We'll ultimately host the site on S3.
