### ISSUE TITLE
digitizer: error getting export from the pi, crashes the whole wheel

### ISSUE THREAD

**Issue by emilyeros** [sharedstreets/curb-wheel#118]
May have to do with overly long mapped street segments - I had graph segmentation issues and exceeded the street length by a lot. Though that should just be proportionally scaled to the street length.

Data export files and raw graph uploaded to google drive in case that helps diagnose.

<img width="1787" alt="Screen Shot 2020-07-29 at 9 25 00 AM" src="https://user-images.githubusercontent.com/9657971/88842221-f8a23880-d193-11ea-9a46-4a3b507f4e5d.png">

**Comment by russbiggs** [comment]
After testing last week this doesn't seem to be an issue with the graph segmentation or the frontend, likely an issue in the upgrade process. Closing for now we can reopen if the problem persists
