### ISSUE TITLE
Render MB tiles on the phone

### ISSUE THREAD

**Issue by emilyeros** [sharedstreets/curb-wheel#12]
Few different options:
- Tessera + MB tiles npm module
- OpenMapTiles (feedback: bulkier/more complicated)
- other things on Kevin's list

**Comment by morganherlocker** [comment]
Another option is to build and serve vector tiles directly using geojson-vt:

https://github.com/mapbox/geojson-vt

**Comment by kpwebb** [comment]
merged in tileserver-gl-light configuration optiosn for serving vector tiles in #29 . requires openmaptiles mbtiles file.

**Comment by emilyeros** [comment]
shipped
