### ISSUE TITLE
POIs on basemap

### ISSUE THREAD

**Issue by russbiggs** [sharedstreets/curb-wheel#121]
I poked around in the OpenMapTiles MBtiles and found the bundle does contain POIs they just arent being rendered with the current TileServer style. While we will still face issues with the 2017 vintage of the download for more permanent POIs they may be relevant enough to provide a bit more context when navigating around.  @peterqliu do you have any experience in creating tileserver-gl style JSON and do you think adding POI labels, (and maybe polygon labels) is feasible?

**Comment by russbiggs** [comment]
We can (and maybe should) continue looking into more recent vector tile sources since the OpenMapTiles 2017 data is pretty old and in some cities fairly different (e.g. Albuquerque) but an update to the JSON maybe provide a fix in the short term

**Comment by peterqliu** [comment]
indeed ✨ though my simulator struggles to fetch the style from `http://10.3.141.1:8080/` (Bad Request?) so I'm referring to a hardcoded version of the style stored at `app.constants.mapStyle.fullStyle`. Might be different when connected to the Pi though.

<img width="773" alt="Screen Shot 2020-07-30 at 8 04 42 PM" src="https://user-images.githubusercontent.com/4551508/88995681-24124980-d2a0-11ea-8726-77bba375a9a4.png">

**Comment by russbiggs** [comment]
Oooh that looks nice to me.  In simulator if you trade out 10.3.141.1 for localhost or 127.0.0.1 it _should_ work. Though the 10.3.141.1 will work on pi!

**Comment by russbiggs** [comment]
@emilyeros @molliemcardle Do you think a style like the above would improve on-the-ground navigation with the POI labels?

**Comment by molliemcardle** [comment]
@russbiggs I think if this is a quick fix for our POI issue, it looks great.

**Comment by emilyeros** [comment]
I like it! Could we change the font from a blue-ish to a brown-ish so it's the same color family as the buildings, rather than as the streets/lines?

**Comment by emilyeros** [comment]
@molliemcardle do you mind testing this and seeing how much it helps with orientation?

**Comment by molliemcardle** [comment]
I tested this and found it to be an extremely helpful addition for navigation. @russbiggs noted that some of these may be out of date but for now we decided having them is better than not.
