### ISSUE TITLE
Segment distance calculations

### ISSUE THREAD

**Issue by russbiggs** [sharedstreets/curb-wheel#122]
Curbwheel's distance calculations can be significantly off from on-the-ground realities. Testing on a small triangular median island with some parking restrictions Curbwheel reports ~39m for one segment of the triangle, while measuring with a Adirpro yields 23m corner to corner, 16 meters difference. 

This error is coming from a couple sources, i.e. turf's Haversine and how graph segmentation is splitting ways, but might be worth brainstorming ways to minimize this error.

**Comment by emilyeros** [comment]
addressed - this was a bounce signal issue
