### ISSUE TITLE
Architecture review 

### ISSUE THREAD

**Issue by kpwebb** [sharedstreets/curb-wheel#127]
@russbiggs and I are conducting a review of the wheel architecture and design. We curious if revisiting some of the core assumptions around how the wheel/phone are linked can help resolve some of the lingering implementation issues. These include:

1. Pi processing power limiting our ability to process large areas of a city.
2. Single core processor leading to moments of non-responsiveness that undermine user experience
3. Restrictions on non-SSL HTTP connections limiting in-browser functionality like GPS location puck
4. Inability to leverage existing SharedStreets segmentation and public map tiles due to lack of internet connectivity
5. Complex deployment and upgrade process slowing development and limiting our ability to automate testing

Current exploration includes:

- [x] validation of BLE/Cordova architecture for moving current collector app to phone
- [ ] validation of SharedStreets segmentation as an alternative to current bespoke, on-wheel OSM processing workflow
- [ ] validation of cordova local storage restrictions
- [ ] can we use HTML media API in cordova-land for camera access?

@russbiggs and I are working on minimum viable tests for each of these questions that can be carried out this week, and help estimate overall effort required to make change and confirm the change actually resolves outstanding issues outlined above.

**Comment by emilyeros** [comment]
closed - invetigated and addressed these aspects before building the new app
