### ISSUE TITLE
Cordova Camera Discussion

### ISSUE THREAD

**Issue by russbiggs** [sharedstreets/curb-wheel#128]
This can be a space to review the pros/cons and issues around using camera APIs on Cordova. 

* ``` cordova-plugin-camera ```

A couple options around storing the photos after accessing camera and taking the photo:

* Access native photo gallery and store File URI as documented in camera plugin ``` Camera.DestinationType.FILE_URI```
* Store image data in SQLite to custom access and storage
   * Base64 text?
   * Bytes BLOB?

**Comment by emilyeros** [comment]
closed - issue addressed as part of app overhaul
