### ISSUE TITLE
PARTS.md

### ISSUE THREAD

**Issue by morganherlocker** [sharedstreets/curb-wheel#2]
Markdown file with a parts purchase list.

## notes

- prefer adafruit or sparkfun for suggestions on pi zero and microsd (steer away from fakes)
- thingverse link for ordering preprinted wheel case
- add disclaimer about golden path hardware we support

**Comment by emilyeros** [comment]
I've added a draft list of parts that I kept track of as i wrote set up instructions. It will need to be fleshed out and additional guidance given about micro SD cards, etc

**Comment by morganherlocker** [comment]
Looks great! I added links for the microsd card and reader I am using. Let's open new issues if we need to make additional changes, now that we have the basic list in place.
