### ISSUE TITLE
Select a CSS framework for the UI

### ISSUE THREAD

**Issue by emilyeros** [sharedstreets/curb-wheel#27]
Need a framework for building the front-end of the mapping web app. Suggestions from @morganherlocker :

1. https://bulma.io/documentation/overview/
2. https://getbootstrap.com/

**Comment by morganherlocker** [comment]
From chat, we agreed that bulma seems like a good fit. I have bulma working in offline mode on the `overworld` branch, which will merge in today.

**Comment by morganherlocker** [comment]
This shipped: https://github.com/sharedstreets/curb-wheel/pull/32
