### ISSUE TITLE
switch express server to non-protected port and proxy with nginx?

### ISSUE THREAD

**Issue by kpwebb** [sharedstreets/curb-wheel#30]
Running express on Port 80 requires root permissions. Should we use a non-reserved port (e.g. 8080) and proxy via nginx? Alternatively have to run node as a root both on pie and/or desktop for testing.

**Comment by morganherlocker** [comment]
Update: We are currently running on ports 8080 and 8081. ngnix may still be a good idea to mix these onto a single port.

**Comment by emilyeros** [comment]
closed - no longer relevant bc of app overhaul
