### ISSUE TITLE
preserve collection state on server to allow browser refreshes on client

### ISSUE THREAD

**Issue by kpwebb** [sharedstreets/curb-wheel#31]
- store collection session state on server 
- define minimum viable session state file format
- define api for posting and retrieving session state

**Comment by morganherlocker** [comment]
This exists now. Committed sessions live in the graph, and the graph has serialization and de-serialization methods for saving and loading from disk. The in memory structure uses a few non JSON data structures, and the methods convert to/from these structures. The user is able to access this state through the bounding box query endpoint, which contains all the info about each edge. For persisting to disk, we'll save a copy of graph whenever a significant event occurs (street checked in).
