### ISSUE TITLE
change ap configuration to use RaspAP project installer

### ISSUE THREAD

**Issue by kpwebb** [sharedstreets/curb-wheel#35]
Ran into lots of trouble getting AP settings configured but switched over to using RaspAP project installer and worked flawlessly:

https://github.com/billz/raspap-webgui/

Let's discuss what's actually working/not working with AP config and see if we need to switch setup process to use this configuration.

**Comment by emilyeros** [comment]
closed - we have an image for initially flashing the wheel and then never need to touch the pi software again. yay.
