### ISSUE TITLE
simplify switch between AP and local network mode

### ISSUE THREAD

**Issue by kpwebb** [sharedstreets/curb-wheel#37]
Per changes in #35 we need to make toggling between AP and wifi mode simpler. Current steps involve (WIP):

**Comment by kpwebb** [comment]
Steps for switching from AP to Wifi mode:
```
# 1. configure local wifi network in /etc/wpa_suplicant/wpa_suplicant.conf 
# 2. save raspapd DHCP config
sudo cp /etc/dhcpcd.conf /etc/raspap/backups/dhcpcd.conf.ap
# 3. swap in backup of original DHCP config
sudo cp /etc/raspap/backups/dhcpcd.conf /etc/dhcpcd.conf
# 4. disable raspapd service 
sudo systemctl disable raspapd.service

```

**Comment by emilyeros** [comment]
not sure if github is the right place for this, but to keep instructions accessible and not lost in slack, here's the workaround for using SSHFS in the meantime:
- documentation: https://www.raspberrypi.org/documentation/remote-access/ssh/sshfs.md
- can install on mac with https://osxfuse.github.io/ (first download on that page)
- once installed, follow `Usage` instructions

cc @molliemcardle

**Comment by emilyeros** [comment]
closed - issue addressed as part of app overhaul
