### ISSUE TITLE
install py counter for simplified wiring on image

### ISSUE THREAD

**Issue by kpwebb** [sharedstreets/curb-wheel#4]

**Comment by kpwebb** [comment]
Added #16

**Comment by emilyeros** [comment]
Success! But the counting seems to skip a beat or start incrementing in 10s instead of in 1s. We'll test and tweak this. Leaving this note just to keep track of things.

**Comment by morganherlocker** [comment]
This shipped. The debounce time is configurable in the version currently on master.
