### ISSUE TITLE
Handle UI confirmation dialogs gracefully

### ISSUE THREAD

**Issue by peterqliu** [sharedstreets/curb-wheel#48]
The frontend uses browser prompts for users to confirm big actions, like deleting/ending curb zones, leaving the current survey, and providing instructions for photography. This brings up two specific challenges:

- As a user surveys many curbs and regulations in a session, all the confirm dialogs can get unnecessary and bothersome

- Some browsers let users disable dialogs entirely. Since these actions are gated by pressing the dialog `OK`, disabling them means not being able to do these actions at all. Unfortunately, there's no way in Javascript to see if a user has disabled prompts.

**Comment by peterqliu** [comment]
Current plan

- To avoid repetition, show confirm dialog once for each action, per session. All subsequent actions of the same kind will go straight to the `OK` state.

- There's a hack that checks for disabled dialogs by [measuring the time between opening the box, and it getting closed](https://stackoverflow.com/questions/20672490/how-to-know-whether-modal-boxes-alert-prompt-confirm-have-been-disabled-i). Under the hood, browsers disable them simply by programmatically pressing `Cancel` the instant they pop up. If this workaround is reliable, we can go straight to the `OK` state if we detect disabled dialogs.

**Comment by emilyeros** [comment]
👍 will add to this week's milestone

**Comment by peterqliu** [comment]
https://github.com/sharedstreets/curb-wheel/pull/68
