### ISSUE TITLE
mbtiles admin upload UI

### ISSUE THREAD

**Issue by morganherlocker** [sharedstreets/curb-wheel#55]
Add a UI form that allows user to drag and drop a mbtiles file that will serve vector tiles for the overworld map.

**Comment by morganherlocker** [comment]
This shipped.

**Comment by kpwebb** [comment]
the

**Comment by kpwebb** [comment]
Need to figure out setup

**Comment by emilyeros** [comment]
fyi when using with simulator: tile server doesn't reset after uploading new data, so the new mbtiles don't display. have to manually restart tile server.

**Comment by morganherlocker** [comment]
This shipped yesterday.
