### ISSUE TITLE
upload images from client

### ISSUE THREAD

**Issue by morganherlocker** [sharedstreets/curb-wheel#59]
Get the client to upload images to the POST server endpoint before uploading the survey.

**Comment by emilyeros** [comment]
if possible, it would be helpful to include these properties into the EXIF data for each image:
- lat/long coordinates from its adjusted position distance on the street
- position id ("pos_id")
- timestamp (should already be included)

if you're busy, this isn't urgent for this week

**Comment by peterqliu** [comment]
to my understanding, the camera app adds EXIF metadata automatically (except not the position id)

**Comment by emilyeros** [comment]
right, but GPS coordinates will be based off phone GPS, which will be
different and less accurate than the position coordinates we work out. this
isn't a need-to-have feature request, but it does enable some mapping
platforms to position the image on a map for viewing

**Comment by morganherlocker** [comment]
This might be challenging to hack into the EXIF data, but our survey format does support linear `Span` geometries, which I think is what we're looking for. This means we could go back and add them to the EXIF tag if the feature is required to be encoded in the image for any reason.

**Comment by morganherlocker** [comment]
Client image uploads are implemented and working. There are some remaining issues reported on the export side, which we will continue to track there.
