### ISSUE TITLE
Web app design

### ISSUE THREAD

**Issue by emilyeros** [sharedstreets/curb-wheel#6]
## Current thinking
The current working design for the web app is shown below.

1. Home screen shows the area of interest with streets color-coded by what has / hasn't been surveyed. The user taps on a blockface to map to begin surveying.
2. User starts at one end of the street, wheeling along the curb with the direction of traffic. (We discussed and discarded the idea of manually tapping on a start location). When the user reaches a curb asset, they will pause the measurement if necessary (they might have to back up to take a clear photo), tap the start/middle/stop button to enter photo mode
3. The user snaps one or more photos of the asset. (The LR and other geo info can be added as a custom EXIF header to help tie the photo to the street segment.)
4. If the measurement is paused, it must be unpaused in order to resume surveying

![IMG_0817](https://user-images.githubusercontent.com/9657971/77390821-50e3ac80-6d54-11ea-909a-3aa3711c63aa.jpg)

## Issue
This interface design is simple, sticking to one surveying screen with a handful of buttons. However, we're not getting enough info here to capture segments - we would end up with LR'd points that mark the start, middle, or end of a segment... but we don't know which points go together. We can't maintain multiple states. Because curb regulations often overlap, we can't make sense of the output with this app design. This potentially doubles the amount of work for the digitization stage, since each point is handled individually instead of as a segment.

## Potential solution
To maintain multiple states, we need the buttons to be activated and deactivated, so that we're capturing a segment (and its associated photo(s)) instead of two individual points. Doing this generically (buttons named "State 1", "State 2", etc) is possible but it puts a burden on users to remember what was what. So it's preferable to do this with words, to capture whether the asset is a parking zone, curb cut, etc. Capturing the asset category also reduces the digitization workload later.

The categories need to be specific enough that users can remember what's what, but generalizable enough that we don't have clutter from overly specific buttons (or try to capture all eventualities, and end up with exceptions that don't fit).

Here's a quick sketch:

<img width="590" alt="Screen Shot 2020-03-23 at 10 49 09 PM" src="https://user-images.githubusercontent.com/9657971/77392590-8be7df00-6d58-11ea-9a21-0159bf689c5e.png">

Thoughts?

**Comment by emilyeros** [comment]
Here's what I translated from Kevin's images. I tried it with a pause button but removed it after our conversations - we can think about diff ways to do that implicitly.

1.Home screen
![IMG_1085](https://user-images.githubusercontent.com/9657971/78720495-aa161900-78da-11ea-90d9-88af7879f460.JPG)

2. Zoom to screen selector
![IMG_1086](https://user-images.githubusercontent.com/9657971/78720644-e9446a00-78da-11ea-93da-e8179468a408.JPG)


3. Create "zone"
![IMG_1087](https://user-images.githubusercontent.com/9657971/78720655-ee091e00-78da-11ea-8019-cdd7c16ed11f.JPG)

4. Zone specifier
![IMG_1088](https://user-images.githubusercontent.com/9657971/78720680-f82b1c80-78da-11ea-87aa-329396d8337d.JPG)

5. Add photo / end zone
![IMG_1089](https://user-images.githubusercontent.com/9657971/78720715-07aa6580-78db-11ea-8a27-4b08e5bd1a27.JPG)

6. Capture image
![IMG_1092](https://user-images.githubusercontent.com/9657971/78720747-1729ae80-78db-11ea-922a-3273fd3e0df7.JPG)

7. Surveying screen shows zones (as offset lines)
![IMG_1091](https://user-images.githubusercontent.com/9657971/78720766-1ee95300-78db-11ea-96ff-88aa85269764.JPG)

**Comment by emilyeros** [comment]
Feedback from @morganherlocker for the above version:

1. i think for screens with a map, we'll want to be real careful with arrangement to make things accessible. pinch zoom in particular can be tough on narrow maps, so im wondering if a layout that puts buttons below the map could work
2. also wondering if we need the map on the main rolling screen (need a better name for this). maps generally dont work on a phone unless they are full screen or close to it
3. idk if this would work or not, but the ideal layout would be to have a progress bar instead of a map [on the rolling screen]. ("ideal" from a layout and performance perspective; not necessarily from a visualization perspective). stuff like [screen 7] could get really messy, since the zoom is not fixed. I'm wondering if a simplified vizualization might be better.
4. Re: pause button [which we decided to kill]. last note, i'm still kinda wondering what the point of pause and unpause is. if the wheel is getting moved around and not set down in exactly the same spot, this will add unknown levels of error into the measurements. is it reasonable to tell users "use the kickstand when you take a photo; you can walk away from the wheel while doing this."
4.

**Comment by molliemcardle** [comment]
1. there should be a '+' button on every screen to enable users to run multiple regulations at the same time. 
2. determining the proper start location is tricky. Could we add a note to start from the edge of the curb ramp or corner?

**Comment by morganherlocker** [comment]
This design was the basis for our current implementation. Closing so we can focus on targeted implementation and design issues on a feature by feature level.
