### ISSUE TITLE
Validate survey contents before returning to map view

### ISSUE THREAD

**Issue by emilyeros** [sharedstreets/curb-wheel#64]
When a user taps the button to complete a survey, it should check:

### That all span-type features have a beginning and an end. 
If there are open spans, prompt user with dialog box that warns them about one or more open spans. We could force the user to return to the survey mode to close spans manually. Or we could show two buttons: one to go back to the survey to correct this, and one to close all open zones and continue exiting the survey.

### The difference between reference length and surveyed distance. 
Conditions for a warning should prob be different depending on whether the surveyed distance is less than or greater than reference length, due to intersection offsets. Warn if: 
- Surveyed length is less than reference length by a difference of >20% of ref length
- Surveyed length is greater than reference length by a difference of >10% of ref length
Either condition should prompt use with a warning dialog and an option to start over on the street survey or else save and continue.

I don't think it should warn users if there's a feature that's created that doesn't have a photo. It may be best practice to take a photo for most features, but warning dialogs would get annoying pretty quickly.

**Comment by emilyeros** [comment]
ps wasn't sure if we're adding this for this week's release - you can add the `v1 blocker` label if so

**Comment by morganherlocker** [comment]
@peterqliu I added a comment in the uploadSurvey function to let you know where the handoff can occur when you get a successful 200 status code. The xhr API is a bit... unintuitive. :stuck_out_tongue_winking_eye:

**Comment by peterqliu** [comment]
the above basics are covered in https://github.com/sharedstreets/curb-wheel/pull/68, though we'll likely add to this. @emilyeros feel free to reopen this when that happens 👍
