### ISSUE TITLE
Default feature label/geom options

### ISSUE THREAD

**Issue by emilyeros** [sharedstreets/curb-wheel#66]
The app currently has the following options for adding a "zone" to the street:

- 'Parking'
- 'No Parking'
- 'Stopping'
- 'No Stopping' 
- 'Loading'
- 'Standing'
- 'No Standing' 
- 'Travel Lane'

Let's try out the following for our first round of testing. I know this is a mix of assets and regs, but let's give it a go anyway. I've included the geometry type in parentheses.

- Parking (span)
- No parking (span)
- Loading (span)
- No stopping (span)
- Curb cut (span)
- Paint (span)
- Other zone (span)
- Payment device (position)
- Fire hydrant (position)
- Other point (position)

Button to add these should be "add feature" instead of "add zone"

**Comment by emilyeros** [comment]
note: there could be instances where a feature fits into more than one category. that's fine - it doesn't really matter which label someone uses (it's just for sorting later). there just always needs to be at least one label for whatever someone sees on the street.

**Comment by peterqliu** [comment]
starting on this now -- flagging that this is a major lift, as it breaks the previous span-only framework for data, rolling behavior, available actions, and progress bar UI, in order to accommodate positions

**Comment by emilyeros** [comment]
okay. this is something we could bump to a later version if you want to prioritize other things.

**Comment by peterqliu** [comment]
Nah, the sooner we tackle this piece the better. I've implemented a lot of the changes in [this commit](https://github.com/sharedstreets/curb-wheel/pull/68/commits/3b8c7164b0e9107970e17eef1ca3f9dba98c15be#diff-80e665266d696d080a310b3b372f5f34R19-R35):

### Semantics and data
- **Transition from "zone" to "feature" terminology**:  but the presence of `position` things means that not everything is a zone anymore. Not comprehensive yet, but moving toward "curb feature" or "feature".

- **Updated feature types**: the constants have been modified from a list to an [object](https://github.com/sharedstreets/curb-wheel/pull/68/commits/3b8c7164b0e9107970e17eef1ca3f9dba98c15be#diff-80e665266d696d080a310b3b372f5f34R19-R35) distinguishing positions from spans.

- **New handling of data**: each feature now has a type attribute of "position" or "feature". When added positions will immediately terminate, with an `end` time the same as the `start`. This will continue to change a bit as @morganherlocker helps me adopt the backend data model on the front side here.

### UI
- **Updated "add Feature" modal**: the above constants will populate the "buttons screen". Buttons are now full-width to accommodate odd numbers of feature types.

![image](https://user-images.githubusercontent.com/4551508/82248974-e38c6c00-98fd-11ea-8798-63509b07817c.png)

- **New progress bar indicator**: diamond to denote positions, differentiating from spans.
![image](https://user-images.githubusercontent.com/4551508/82249372-8349fa00-98fe-11ea-9f2e-09f7b12fd62e.png)

- **New feature actions**: previously, users could delete/photograph/complete a span until they complete it, at which time all these options disappear. Lacking a span distance, the new `position` type immediately completes itself upon adding, making it impossible to add a photo of it.

To avoid the complexity of different action UIs for different feature types, all features can now be deleted and photographed throughout the survey, even after spans are completed:

![image](https://user-images.githubusercontent.com/4551508/82250192-dc665d80-98ff-11ea-930e-28b4877d036b.png)

After completion:

![image](https://user-images.githubusercontent.com/4551508/82250207-dff9e480-98ff-11ea-9557-30c0e3e7e228.png)

**Comment by peterqliu** [comment]
https://github.com/sharedstreets/curb-wheel/pull/68
