### ISSUE TITLE
change file permissions to ease software updates

### ISSUE THREAD

**Issue by emilyeros** [sharedstreets/curb-wheel#67]
Files that I can't currently delete:
- `config/wpa_supplicant.conf.template` (might be settings on whole `config` directory)
- all files in `tileserver` directory (includes: `2017-07-03_us_hawaii.mbtiles`, `setup-tileserver.sh`)
- all files in `src` directory (includes: `graph.js`, `server.js`)

**Comment by kpwebb** [comment]
Ok! Got upgrade process that works from recent images (e.g r8).

Here are the steps:

1 .Update github directory on wheel
  a. connect to wheel using curbwheel-ap wifi network
  b. Copy new directory from laptop via ssh (first time running will prompt for pi password)
     `sh upgrade_wheel.sh` 
2 Flash image using dd
   - Insert SD card on mac and find drive
      `diskutil list` 
      `sudo dd if=/dev/disk2  | gzip > ~/Desktop/curbwheel_image_r8.img.gz`
- Copy image file to s3 bucket

**Comment by emilyeros** [comment]
👍 this looks doable. thanks!

**Comment by emilyeros** [comment]
successfully executed this, creating r9.
