### ISSUE TITLE
User location puck

### ISSUE THREAD

**Issue by morganherlocker** [sharedstreets/curb-wheel#83]
We have the user location and bearing, when permission is granted and browser support is available. We need to add three features to implement map navigation similar to big consumer maps:

- continuously poll for location and heading (it's just a different geolocation API call)
- draw a puck circle with some bearing indication when location is updated
- add a button for centering the map of user location at high zoom

My sense from reviewing several consumer apps is that the map does not follow the user, but the puck does. Navigation apps do make the map follow the user, but only during active turn-by-turn routing. We can explore this as well, but we'll need a "disengage" mechanic like nav apps do.

**Comment by emilyeros** [comment]
Shipped. Tracked in https://github.com/sharedstreets/curb-wheel/issues/85
