### ISSUE TITLE
Determine maximum pbf size on pi zero

### ISSUE THREAD

**Issue by morganherlocker** [sharedstreets/curb-wheel#84]
We are seeing pbf extract failing on the pi with >1mb osm pbf files. Not sure what is going on here, so I can benchmark on my pi with various size extracts. There could be a bug or memory leak, in which case, I can patch this to support larger files. Either way, we need to document a max supported size and validate this in the admin panel.

**Comment by emilyeros** [comment]
Boston had some trouble with their citywide PBF, but everyone with exports >10MB was able to set up their wheel successfully. Closing this issue.

**Comment by emilyeros** [comment]
relevant pr: https://github.com/sharedstreets/curb-wheel/pull/87
